feat(strm-1259): remove billing id usage
strmprivacy/java-driver pull request #13
Opened 2022-07-05 09:08 UTC by bobvandenhoogen

2022-07-05 12:13 UTC, trietsch requested changes

2022-07-05 12:13 UTC, trietsch commented on lib/src/main/java/io/strmprivacy/driver/client/AuthService.java
> +                .header("content-type", "application/x-www-form-urlencoded")
You can use the `HttpHeader` constants.

2022-07-05 12:13 UTC, trietsch commented on lib/src/main/java/io/strmprivacy/driver/domain/Config.java
> +        setKeycloakUrl(builder.keycloakUrl);
For consistency sake, please split the URL parts, as before.

2022-07-05 12:13 UTC, trietsch commented on lib/src/test/java/io/strmprivacy/driver/client/StrmPrivacyClientTest.java
> +                .keycloakUrl("https://accounts.dev.strmprivacy.io/auth/realms/streams/protocol/openid-connect/token")
Did you actually update the test itself? You should create the specific mocks with Wiremock in order to properly test it.

2022-07-05 13:51 UTC, trietsch requested changes

2022-07-05 13:51 UTC, trietsch commented on lib/src/main/java/io/strmprivacy/driver/client/AuthProvider.java
> +    private String access_token;
Use pascal case.

2022-07-05 13:51 UTC, trietsch commented on lib/src/main/java/io/strmprivacy/driver/client/AuthProvider.java
> +    public String getAccess_token() {
casing?

2022-07-05 13:51 UTC, trietsch commented on lib/src/main/java/io/strmprivacy/driver/domain/Config.java
> +        private String keycloakEndpoint = "auth/realms/streams/protocol/openid-connect/token";
Convention is to start paths on a host with `/`.

2022-07-05 13:51 UTC, trietsch commented on lib/src/main/java/io/strmprivacy/driver/client/AuthService.java
> +            this.authUri = new URI(String.format("%s://%s/%s", config.getKeycloakScheme(), config.getKeycloakHost(), config.getKeycloakEndpoint())).toString();
The slash should be removed here for the path. That should be included in the path parameter.

2022-07-05 14:30 UTC, trietsch requested changes
Once we can merge this, **this PR should be merged as breaking change**

2022-07-05 14:31 UTC, trietsch approved these changes
Approved, but once we can merge this, **this PR should be merged as breaking change**

2022-07-07 08:16 UTC, ivan-p92 approved these changes

2022-07-12 13:09 UTC, merged

2022-07-12 13:10 UTC, strmprivacy-io commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on [GitHub release](https://github.com/strmprivacy/java-driver/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: